### ISSUE TITLE
Possible DRP issue when launching several massively parallel jobs

### ISSUE THREAD

**Issue by fredericpoitevin** [lcls-users/btx#109]
On a few occasions, when a lot of runs were being processed together, we started seeing slurm jobs not exiting, sometimes linked with failure in executing the python task.

For example, peak finding of run 10 of mfxlx5520 was launched through eLog/Airflow with the following arguments:
```bash
-d index_run -q ffbh4q -n 128 -c /cds/sw/package/autosfx/btx/tutorial/mfxlx5520_nocell_ffb.yaml
```

It initially failed with the following error (SLURM ID 393557):
```python
Error: Task failed.
Traceback (most recent call last):
  File "/cds/sw/package/autosfx/btx/scripts/main.py", line 42, in <module>
    retval, status_message = main()
  File "/cds/sw/package/autosfx/btx/scripts/main.py", line 36, in main
    globals()[task](config)
  File "/cds/sw/package/autosfx/btx/scripts/tasks.py", line 131, in find_peaks
    pf.curate_cxi()
  File "/cds/sw/package/autosfx/btx/btx/processing/peak_finder.py", line 235, in curate_cxi
    outh5['/entry_1/data_1/data'].resize((self.n_hits, data_shape[1], data_shape[2]))
  File "/cds/sw/ds/ana/conda1/inst/envs/ana-4.0.38-py3/lib/python3.7/site-packages/h5py/_hl/dataset.py", line 597, in resize
    self.id.set_extent(size)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5d.pyx", line 285, in h5py.h5d.DatasetID.set_extent
ValueError: Unable to set extend dataset (addr overflow, addr = 17512, size = 3136, eoa = 17512)
``` 

While the same job after beamtime - with less activity on disk maybe? - succeeded (SLURM ID 393605):
```python 
Task successfully executed
```

**Comment by fredericpoitevin** [comment]
Will try reducing the number of parallel tasks to 64 tomorrow to see if that helps.

**Comment by fredericpoitevin** [comment]
A much more likely cause for this problem: we launched two `index_run` at the same time on each run, for a while - one with known unit cell, and another one without. Since the first step in each DAG consists in peak finding - which is independent from the unit cell - what happened is that both dag runs were writing to CXI files with the same path, in a possible very weird way.

**Comment by fredericpoitevin** [comment]
The issue was solved by making sure `.cxi` files were not accessed by two `indexing` runs - making good use of tags.
