### ISSUE TITLE
Users can't run tasks that rely on writing and executing a script

### ISSUE THREAD

**Issue by fredericpoitevin** [lcls-users/btx#172]
The issue encountered is a user can't index their data while I can do it for them:
```bash
[fpoitevi@drp-srcf-eb001 launchpad]$ pwd
/cds/data/drpsrcf/mfx/mfxlx5520/scratch/xzordo/launchpad
[fpoitevi@drp-srcf-eb001 launchpad]$  submit_range_run.sh -c ../yamls/highPh_ox_97to120.yaml -n 64 -r 97 -s 98 -t index
```

I suspect it has to do with the `self.tmp_exe` script that is written to `/cds/sw/package/autosfx/btx/scripts/` by the `Indexer` class. That directory is not writable to users not in the `ps-data` group.

**Comment by fredericpoitevin** [comment]
Thanks to Sandra for pointing out that this was still a problem:
```bash
(ana-4.0.45-py3) [fpoitevi@drp-srcf-eb003 launchpad]$ cat slurm-484226.out
ana-4.0.45-py3        *  /cds/sw/ds/ana/conda1/inst/envs/ana-4.0.45-py3
/cds/sw/ds/ana/conda1/inst/envs/ana-4.0.45-py3/bin/mpirun
/cds/sw/ds/ana/conda1/inst/envs/ana-4.0.45-py3/bin/python
new config file: ../yamls/mfxx49820_14.yaml
/cds/sw/ds/ana/conda1/inst/envs/ana-4.0.38-py3/bin/python /cds/sw/package/autosfx/btx/scripts/main.py -c ../yamls/mfxx49820_14.yaml -t index
DEBUG:scripts.tasks:Generating indexing executable for run 14 of mfxx49820...
Traceback (most recent call last):
  File "/cds/sw/package/autosfx/btx/scripts/main.py", line 42, in <module>
    retval, status_message = main()
  File "/cds/sw/package/autosfx/btx/scripts/main.py", line 36, in main
    globals()[task](config)
  File "/cds/sw/package/autosfx/btx/scripts/tasks.py", line 164, in index
    indexer_obj.launch()
  File "/cds/sw/package/autosfx/btx/btx/processing/indexer.py", line 89, in launch
    js.write_header()
  File "/cds/sw/package/autosfx/btx/btx/interfaces/ischeduler.py", line 57, in write_header
    with open(self.jobfile, 'w') as jfile:
PermissionError: [Errno 13] Permission denied: '/cds/sw/package/autosfx/btx/scripts/task_c0d9d630-7508-4e05-a634-1f14c4c3a878.sh'

Error: Task failed.
```

The change in `elog_submit.sh` made here was [later reverted back](https://github.com/lcls-users/btx/commit/0246985c36cd0d3e759edab26963fa548fec970e), possibly thinking that #180 would solve the problem.
