### ISSUE TITLE
`IndexError` in `run.py`

### ISSUE THREAD

**Issue by fredericpoitevin** [lcls-users/btx#238]
In `/cds/data/drpsrcf/mfx/mfxl1013721/scratch/slurm-552146.out`:
```bash
/cds/sw/package/autosfx/btx/btx/diagnostics/run.py:67: RuntimeWarning: invalid value encountered in sqrt
  self.powders_final['std'] = np.sqrt(np.sum(powder_sqr, axis=0) / float(total_n_proc) - np.square(self.powders_final['avg']))
Traceback (most recent call last):
  File "/cds/sw/package/autosfx/btx/scripts/main.py", line 42, in <module>
    retval, status_message = main()
  File "/cds/sw/package/autosfx/btx/scripts/main.py", line 36, in main
    globals()[task](config)
  File "/cds/sw/package/autosfx/btx/scripts/tasks.py", line 84, in run_analysis
    gain_mode=task.get('gain_mode'))
  File "/cds/sw/package/autosfx/btx/btx/diagnostics/run.py", line 226, in compute_run_stats
    self.finalize_powders()
  File "/cds/sw/package/autosfx/btx/btx/diagnostics/run.py", line 74, in finalize_powders
    self.panel_mask = assemble_image_stack_batch(np.ones(self.psi.det.shape()), self.pixel_index_map)
  File "/cds/sw/package/autosfx/btx/btx/interfaces/ipsana.py", line 342, in assemble_image_stack_batch
    images[:, pixel_index_map[l, :, :, 0], pixel_index_map[l, :, :, 1]] = image_stack[:, l, :, :]
IndexError: too many indices for array: array is 2-dimensional, but 4 were indexed

Error: Task failed.
```

**Comment by apeck12** [comment]
Closed by PR #239.
