### ISSUE TITLE
`TypeError` when an event does not have an ebeamPhotonEnergy value

### ISSUE THREAD

**Issue by fredericpoitevin** [lcls-users/btx#301]
```bash
DEBUG:scripts.tasks:Performing peak finding for run 288 of mfxl1013721...
Traceback (most recent call last):
  File "/cds/home/c/cwang31/software/btx/scripts/main.py", line 42, in <module>
    retval, status_message = main()
  File "/cds/home/c/cwang31/software/btx/scripts/main.py", line 36, in main
    globals()[task](config)
  File "/cds/home/c/cwang31/software/btx/scripts/tasks.py", line 166, in find_peaks
    pf.find_peaks()
  File "/cds/home/c/cwang31/software/btx/btx/processing/peak_finder.py", line 328, in find_peaks
    phot_energy = 1.23984197386209e-06 / (self.psi.get_wavelength_evt(evt) / 10 / 1.0e9)
  File "/cds/home/c/cwang31/software/btx/btx/interfaces/ipsana.py", line 113, in get_wavelength_evt
    if np.isinf(photon_energy) or photon_energy is None:
TypeError: ufunc 'isinf' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
...
Warning: event does not have an ebeamPhotonEnergy value.
```

**Comment by gadorlhiac** [comment]
Fixed in PR #320
